### ISSUE TITLE
Error encountered 

### ISSUE THREAD

**Issue by pranairamineni** [abhijeet3922/Change-Detection-in-Satellite-Imagery#2]
(base) D:\Downloads\Change-Detection-in-Satellite-Imagery-master\Change-Detection-in-Satellite-Imagery-master>python PCAKmeans.py
Operating
(1600, 1600) (1600, 1600)

Both images resized to  [1600 1600]

vector_set shape (102400, 25)
Traceback (most recent call last):
  File "PCAKmeans.py", line 119, in <module>
    find_PCAKmeans(a1,b1)
  File "PCAKmeans.py", line 91, in find_PCAKmeans
    FVS     = find_FVS(EVS, diff_image, mean_vec, new_size)
  File "PCAKmeans.py", line 49, in find_FVS
    FVS = np.dot(feature_vector_set, EVS)
MemoryError

**Comment by kjacks21** [comment]
@pranairamineni you are running out of memory. Either decrease the image resolution, use smaller images, or use more RAM.
